import { fromPairs } from 'lodash'

import { Package } from '../core/types'

export const createPackage = ({
  name,
  version = '1.0.0',
  dependencies = {},
  devDependencies = {},
}: Partial<Package>): Package => ({
  name,
  version,
  private: false,
  location: `/packages/${name}/package.json`,
  dependencies,
  devDependencies,
  peerDependencies: {},
  optionalDependencies: {},
})

export const createDep = (name: string, links: string[]) =>
  createPackage({
    name,
    dependencies: fromPairs(links.map((dep) => [dep, '1.0.0'])),
  })

export const graphs = {
  NO_CYCLE: [
    createDep('@foo/a', ['@foo/b', 'react']),
    createDep('@foo/b', ['@foo/a', '@foo/c', 'redux']),
    createDep('@foo/c', ['foo', 'bar', '@foo/d']),
    createDep('@foo/d', ['foo', 'bar', '@foo/e']),
    createDep('@foo/e', ['foo', 'bar']),
  ],
  ONE_CYCLE: [
    createDep('a', ['b', 'c']),
    createDep('b', ['c']),
    createDep('c', []),
    createDep('d', ['a', 'e']),
    createDep('e', ['f']),
    createDep('f', ['d']),
  ],
  TWO_CYCLES: [
    createDep('a', ['b', 'c']),
    createDep('b', ['c']),
    createDep('c', ['a']),
    createDep('d', ['a', 'e']),
    createDep('e', ['f']),
    createDep('f', ['g']),
    createDep('g', ['d']),
  ],
  LARGE_CYCLE: [
    createDep('@foo/1', ['@foo/44', '@foo/43']),
    createDep('@foo/2', []),
    createDep('@foo/3', [
      '@foo/25',
      '@foo/26',
      '@foo/23',
      '@foo/38',
      '@foo/27',
      '@foo/33',
      '@foo/34',
      '@foo/20',
      '@foo/39',
    ]),
    createDep('@foo/4', [
      '@foo/25',
      '@foo/34',
      '@foo/27',
      '@foo/23',
      '@foo/38',
      '@foo/26',
    ]),
    createDep('@foo/5', [
      '@foo/2',
      '@foo/45',
      '@foo/7',
      '@foo/25',
      '@foo/26',
      '@foo/28',
      '@foo/30',
      '@foo/36',
      '@foo/40',
      '@foo/41',
      '@foo/46',
      '@foo/3',
      '@foo/4',
      '@foo/6',
      '@foo/8',
      '@foo/10',
      '@foo/11',
      '@foo/12',
      '@foo/13',
      '@foo/14',
      '@foo/15',
      '@foo/17',
      '@foo/19',
      '@foo/20',
      '@foo/21',
      '@foo/22',
      '@foo/23',
      '@foo/24',
      '@foo/27',
      '@foo/29',
      '@foo/31',
      '@foo/32',
      '@foo/33',
      '@foo/34',
      '@foo/35',
      '@foo/37',
      '@foo/38',
      '@foo/39',
    ]),
    createDep('@foo/6', [
      '@foo/25',
      '@foo/23',
      '@foo/33',
      '@foo/27',
      '@foo/20',
      '@foo/38',
    ]),
    createDep('@foo/7', ['@foo/23']),
    createDep('@foo/8', [
      '@foo/25',
      '@foo/27',
      '@foo/11',
      '@foo/13',
      '@foo/6',
      '@foo/15',
      '@foo/20',
      '@foo/23',
      '@foo/38',
      '@foo/35',
      '@foo/34',
      '@foo/33',
      '@foo/39',
      '@foo/3',
      '@foo/4',
    ]),
    createDep('@foo/9', [
      '@foo/42',
      '@foo/45',
      '@foo/41',
      '@foo/8',
      '@foo/11',
      '@foo/12',
      '@foo/13',
      '@foo/25',
      '@foo/46',
      '@foo/20',
      '@foo/21',
      '@foo/23',
      '@foo/3',
      '@foo/27',
      '@foo/33',
      '@foo/35',
      '@foo/38',
    ]),
    createDep('@foo/10', [
      '@foo/25',
      '@foo/8',
      '@foo/11',
      '@foo/13',
      '@foo/19',
      '@foo/15',
      '@foo/20',
      '@foo/23',
      '@foo/27',
      '@foo/33',
      '@foo/34',
      '@foo/35',
      '@foo/38',
      '@foo/39',
    ]),
    createDep('@foo/11', [
      '@foo/25',
      '@foo/19',
      '@foo/20',
      '@foo/23',
      '@foo/33',
      '@foo/34',
      '@foo/35',
      '@foo/38',
      '@foo/27',
      '@foo/39',
      '@foo/3',
      '@foo/26',
    ]),
    createDep('@foo/12', [
      '@foo/20',
      '@foo/33',
      '@foo/23',
      '@foo/38',
      '@foo/34',
      '@foo/35',
      '@foo/39',
      '@foo/25',
    ]),
    createDep('@foo/13', [
      '@foo/8',
      '@foo/20',
      '@foo/23',
      '@foo/11',
      '@foo/33',
      '@foo/25',
      '@foo/38',
      '@foo/35',
      '@foo/39',
      '@foo/3',
    ]),
    createDep('@foo/14', ['@foo/23', '@foo/11', '@foo/38']),
    createDep('@foo/15', [
      '@foo/11',
      '@foo/20',
      '@foo/21',
      '@foo/23',
      '@foo/35',
      '@foo/38',
    ]),
    createDep('@foo/16', [
      '@foo/42',
      '@foo/45',
      '@foo/25',
      '@foo/5',
      '@foo/20',
      '@foo/21',
      '@foo/14',
      '@foo/23',
      '@foo/33',
      '@foo/39',
      '@foo/35',
      '@foo/38',
      '@foo/46',
    ]),
    createDep('@foo/17', ['@foo/23', '@foo/35', '@foo/25']),
    createDep('@foo/18', ['@foo/20', '@foo/22', '@foo/39', '@foo/46']),
    createDep('@foo/19', ['@foo/23', '@foo/38']),
    createDep('@foo/20', [
      '@foo/25',
      '@foo/30',
      '@foo/31',
      '@foo/32',
      '@foo/3',
      '@foo/21',
      '@foo/23',
      '@foo/37',
      '@foo/27',
      '@foo/33',
      '@foo/35',
      '@foo/38',
      '@foo/39',
    ]),
    createDep('@foo/21', ['@foo/23', '@foo/35', '@foo/38']),
    createDep('@foo/22', ['@foo/46']),
    createDep('@foo/23', [
      '@foo/25',
      '@foo/5',
      '@foo/11',
      '@foo/26',
      '@foo/27',
      '@foo/34',
      '@foo/35',
      '@foo/38',
    ]),
    createDep('@foo/24', [
      '@foo/27',
      '@foo/11',
      '@foo/25',
      '@foo/3',
      '@foo/35',
      '@foo/23',
      '@foo/20',
      '@foo/38',
      '@foo/39',
    ]),
    createDep('@foo/25', []),
    createDep('@foo/26', ['@foo/23', '@foo/38']),
    createDep('@foo/27', [
      '@foo/25',
      '@foo/33',
      '@foo/20',
      '@foo/34',
      '@foo/38',
    ]),
    createDep('@foo/28', [
      '@foo/11',
      '@foo/20',
      '@foo/23',
      '@foo/25',
      '@foo/33',
      '@foo/34',
      '@foo/36',
      '@foo/39',
      '@foo/38',
    ]),
    createDep('@foo/29', [
      '@foo/35',
      '@foo/26',
      '@foo/20',
      '@foo/23',
      '@foo/31',
      '@foo/38',
      '@foo/39',
    ]),
    createDep('@foo/30', [
      '@foo/20',
      '@foo/31',
      '@foo/23',
      '@foo/35',
      '@foo/39',
    ]),
    createDep('@foo/31', [
      '@foo/32',
      '@foo/20',
      '@foo/23',
      '@foo/25',
      '@foo/11',
      '@foo/33',
      '@foo/35',
      '@foo/38',
    ]),
    createDep('@foo/32', [
      '@foo/11',
      '@foo/20',
      '@foo/23',
      '@foo/25',
      '@foo/31',
      '@foo/35',
      '@foo/38',
      '@foo/33',
      '@foo/39',
    ]),
    createDep('@foo/33', ['@foo/25', '@foo/23']),
    createDep('@foo/34', ['@foo/23', '@foo/25', '@foo/26', '@foo/38']),
    createDep('@foo/35', ['@foo/38']),
    createDep('@foo/36', ['@foo/23', '@foo/25', '@foo/34', '@foo/38']),
    createDep('@foo/37', [
      '@foo/25',
      '@foo/23',
      '@foo/38',
      '@foo/27',
      '@foo/33',
      '@foo/34',
      '@foo/20',
      '@foo/39',
    ]),
    createDep('@foo/38', ['@foo/25']),
    createDep('@foo/39', ['@foo/25']),
    createDep('@foo/40', [
      '@foo/11',
      '@foo/20',
      '@foo/23',
      '@foo/25',
      '@foo/33',
      '@foo/34',
      '@foo/36',
      '@foo/39',
      '@foo/38',
    ]),
    createDep('@foo/41', []),
    createDep('@foo/42', ['@foo/46']),
    createDep('@foo/43', []),
    createDep('@foo/44', []),
    createDep('@foo/45', []),
    createDep('@foo/46', []),
  ],
}
